version: '3'

services:
  auth-service:
    image: node:12
    user: 'node'
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - 3000:3000
    command: 'npm start'
